-- Seed the brief library. ~16 builder + ~17 guider briefs across the
-- three complexity buckets (1-3, 4-6, 7-8). Briefs are picked at game
-- create when the GM chooses 'library' as the brief source.

insert into briefs_library (role, complexity_min, complexity_max, title, rules) values

-- ─── Builder briefs ────────────────────────────────────────────────────
('builder', 1, 3, 'Mirror image',
  '["When they say ''left'', place it right.", "When they say ''right'', place it left."]'::jsonb),
('builder', 1, 3, 'Off-by-one',
  '["Any number they say is one more than what you place.", "If they say ''three'', place two."]'::jsonb),
('builder', 1, 3, 'Up is down',
  '["When they say ''up'', go down.", "When they say ''down'', go up."]'::jsonb),
('builder', 1, 3, 'Color cousins',
  '["Treat ''red'' as orange.", "Treat ''yellow'' as green."]'::jsonb),
('builder', 1, 3, 'Read between the lines',
  '["Ignore the first thing they say.", "Act on the second instruction only."]'::jsonb),

('builder', 4, 6, 'Translate, don''t transcribe',
  '["When they say ''left'', place right.", "Treat any color as its complement.", "Halve any number, round up."]'::jsonb),
('builder', 4, 6, 'Helpful pessimist',
  '["Place anything they describe as ''big'' at half size.", "Place anything ''small'' at double size.", "Trust nothing about color names."]'::jsonb),
('builder', 4, 6, 'Stranger at sea',
  '["You only understand directions in the form ''X cells from the centre''.", "Cardinal directions baffle you.", "Ask for clarification before placing anything."]'::jsonb),
('builder', 4, 6, 'Late translator',
  '["Apply each instruction one piece late.", "Hold the latest instruction until the next one arrives.", "On the final instruction, place the held one and the new one."]'::jsonb),
('builder', 4, 6, 'Loose adapter',
  '["Triangles can be replaced with squares.", "Squares can be replaced with hexagons.", "Hexagons must be exact."]'::jsonb),
('builder', 4, 6, 'Centric',
  '["You can only place pieces touching the centre tile.", "If they ask for an outer piece, ask which centre piece it touches first."]'::jsonb),

('builder', 7, 8, 'Three-step delay',
  '["Apply each instruction three pieces late.", "Maintain a queue.", "Reverse the order of any two consecutive instructions before placing.", "Numbers are halved AND mirrored."]'::jsonb),
('builder', 7, 8, 'Reverse perspective',
  '["You see the canvas as the guider does — left/right are flipped.", "Top/bottom are also flipped.", "Colors are inverted (complementary).", "Numbers are doubled."]'::jsonb),
('builder', 7, 8, 'Whisper-down-the-lane',
  '["Each instruction loses one detail in transmission.", "If they say ''big red triangle on the left'', place a ''triangle on the left''.", "Drop the second-most specific descriptor each time."]'::jsonb),
('builder', 7, 8, 'Dialect drift',
  '["Triangle = sail, square = deck, hexagon = buoy. They use the new words; you only know the old.", "Treat any unfamiliar word as ''triangle''.", "Colors are halved in saturation — interpret each as the muted version."]'::jsonb),
('builder', 7, 8, 'Ironic literalist',
  '["When they say ''obviously'', do the opposite.", "When they say ''carefully'', go fast.", "When they say ''roughly'', be precise.", "When they say nothing extra, follow the instruction faithfully."]'::jsonb),

-- ─── Guider briefs ─────────────────────────────────────────────────────
('guider', 1, 3, 'No shape names',
  '["You can never say ''triangle'', ''square'', ''hexagon'', or ''rhombus''.", "Use everyday objects to describe shapes instead."]'::jsonb),
('guider', 1, 3, 'Cardinal only',
  '["You can only use ''north'', ''south'', ''east'', ''west''.", "No left/right/up/down."]'::jsonb),
('guider', 1, 3, 'Plain colors',
  '["Only describe colors using primary names: red, yellow, blue.", "Anything outside those is ''mixed''."]'::jsonb),
('guider', 1, 3, 'Numbers as fractions',
  '["You may only describe distances as halves and quarters of the canvas.", "No specific cell counts."]'::jsonb),
('guider', 1, 3, 'No prepositions',
  '["You can''t use ''above'', ''below'', ''next to'', ''near''.", "Describe each piece independently and trust them to figure it out."]'::jsonb),

('guider', 4, 6, 'Speak only in nautical terms',
  '["Fore/aft, port/starboard.", "Use sail (triangle), deck (square), buoy (hexagon).", "No plain shape names."]'::jsonb),
('guider', 4, 6, 'Only emotions',
  '["Describe each piece by the emotion it evokes.", "''Anxious red''. ''Cheerful triangle''. ''Stoic hex''.", "No literal descriptions."]'::jsonb),
('guider', 4, 6, 'Through a clock face',
  '["The canvas is a clock. Pieces sit at hour positions.", "''A red triangle at 2 o''clock'', ''a green square at 7''."]'::jsonb),
('guider', 4, 6, 'No more than three words',
  '["Each utterance must be three words or fewer.", "Punctuation doesn''t count.", "You may speak many times — just keep each phrase short."]'::jsonb),
('guider', 4, 6, 'In the third person',
  '["You may not say ''I'' or ''you''.", "Refer to the builder by name, or as ''the architect''.", "Speak as if narrating someone else''s building."]'::jsonb),
('guider', 4, 6, 'Through metaphor',
  '["Describe the picture as a story.", "''Two friends meet at a yellow door.''", "No literal coordinates or shape names."]'::jsonb),

('guider', 7, 8, 'Speak only in questions',
  '["Every utterance must end with a question mark.", "''Is the red triangle near the top?''", "You may answer their questions only with another question."]'::jsonb),
('guider', 7, 8, 'No two consecutive nouns',
  '["You cannot follow one noun directly with another.", "Adjectives and verbs must intervene.", "Plan each sentence."]'::jsonb),
('guider', 7, 8, 'Backwards instructions',
  '["State the last piece first.", "Work backwards through the build order.", "Don''t repeat yourself."]'::jsonb),
('guider', 7, 8, 'Double-blind',
  '["You must give two simultaneous instructions, one true and one false, in each utterance.", "''Place a red triangle at the top — or maybe a blue square at the bottom.''", "Builder must guess which is real."]'::jsonb),
('guider', 7, 8, 'Pidgin only',
  '["You may not use grammatical sentences.", "Subject + object + descriptor only, no verbs, no articles.", "''Triangle red top''. ''Square green left bottom''."]'::jsonb),
('guider', 7, 8, 'Whispered urgency',
  '["Every utterance is ten words or more.", "Convey urgency in tone but never name what is urgent.", "Avoid all spatial language; use only sensory description."]'::jsonb);
